import argparse
from pathlib import Path

import yaml

TYPE_MAP = {
    "u1": "UInt8",
    "u4": "UInt32",
    "u64": "UInt64",
    "s1": "Int8",
    "s4": "Int32",
    "s8": "Int64",
    "f4": "Float",
    "f8": "Double",
    "str": "String",
    "common::boolean": "Boolean",
    "common::tilexz": "[TileXZ](common.md#tilexz)",
    "common::color": "[Color](common.md#color)",
    "common::vector2": "[Vector2](common.md#vector2)",
    "common::vector3": "[Vector3](common.md#vector3)",
    "common::rectangle": "[Rectangle](common.md#rectangle)",
    "common::r8string": "[R8String](common.md#r8string)",
    "common::cs_string": "[C# String](common.md#cs_string)",
    "common::matrix4": "[Matrix4x4](common.md#matrix4)",
}


def map_type(ksy_type: str) -> str:
    if ksy_type in TYPE_MAP:
        return TYPE_MAP[ksy_type]
    print(f"Unknown type: {ksy_type}")
    return ksy_type


def parse_ksy(input_file: Path) -> dict:
    with input_file.open("r") as file:
        content = yaml.safe_load(file)
    return content


def parse_doc(doc: str, default_name: str) -> str:
    """
    Extracts n: and d: fields from the doc string into a tuple
    """
    name = default_name
    desc = ""
    split = doc.split(";")

    for part in split:
        if part.startswith("n:"):
            name = part[2:]
        elif part.startswith("d:"):
            desc = part[2:]
    return name, desc


def format_enum(enum_info):
    """
    Formats an enum's values into a markdown table
    """
    markdown = "| Value | Name |\n"
    markdown += "| ------- | ------ |\n"
    for name, value in enum_info.items():
        markdown += f"| {value} | {name} |\n"
    return markdown


def generate_markdown(root: dict, output_file: Path):
    meta = root["meta"]

    with output_file.open("w") as file:
        # autogenerated header
        file.write(f"<!-- This file was autogenerated from {output_file.stem}.ksy. DO NOT EDIT THIS FILE -->\n\n")
        # Title
        file.write(f"# {meta['title']}\n\n")

        # Description
        if "doc" in root:
            file.write(f"{root['doc']}\n\n")

        # Root type
        if "seq" in root:
            file.write("## Root Structure\n\n")
            # Table header
            file.write("| Type       | ID | Description |\n")
            file.write("| ---------- | ---- | ----------- |\n")

            for field in root["seq"]:
                field_id = field["id"]
                field_type = field.get("type", "Bytes")
                field_type_mapped = map_type(field_type)
                is_list = field.get("repeat") != None
                field_enum = field.get("enum")
                field_doc = field.get("doc", "")
                name, desc = parse_doc(field_doc, field_id)
                if field_id.lower().startswith("reserved"):
                    # name = "Reserved"
                    desc = "This field is unused"
                if field_enum:
                    field_type_mapped += f" ([{field_enum}](#enums))"
                if is_list:
                    field_type_mapped += "[]"
                file.write(f"| {field_type_mapped} | {name} | {desc} |\n")
            file.write("\n")

        # Types
        if "types" in root:
            file.write("## Types\n\n")
            for type_name, type_info in root.get("types", {}).items():
                file.write(f"### {type_name}\n\n")
                if "doc" in type_info:
                    file.write(f"{type_info['doc']}\n\n")

                # Table header
                file.write("| Type       | ID | Description |\n")
                file.write("| ---------- | ---- | ----------- |\n")

                # Assuming the fields are in 'seq' (sequence) for structured types
                for field in type_info.get("seq", []):
                    field_id = field["id"]
                    field_type = field.get("type", "Bytes")
                    field_type_mapped = map_type(field_type)
                    is_list = field.get("repeat") != None
                    field_enum = field.get("enum")
                    field_doc = field.get("doc", "")
                    name, desc = parse_doc(field_doc, field_id)
                    if field_id == "reserved":
                        # name = "Reserved"
                        desc = "This field is unused"
                    if field_enum:
                        field_type_mapped += f" ([{field_enum}](#enums))"
                    if is_list:
                        field_type_mapped += "[]"
                    file.write(f"| {field_type_mapped} | {name} | {desc} |\n")

                file.write("\n")

        # Enums
        if "enums" in root:
            file.write("## Enums\n")
            for enum_name, enum_info in root["enums"].items():
                file.write(f"### {enum_name}\n\n")
                file.write(format_enum(enum_info))
                file.write("\n")


def main(input_file: Path, output_dir: Path):
    root = parse_ksy(input_file)
    generate_markdown(root, output_dir / input_file.with_suffix(".md").name)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate markdown documentation from a ksy file")
    parser.add_argument("ksy_file", type=Path, help="The ksy file to parse")
    parser.add_argument("output_dir", type=Path, help="The directory to output the markdown files to")

    args = parser.parse_args()
    ksy_file: Path = args.ksy_file
    output_dir: Path = args.output_dir

    # ensure input file exists
    if not ksy_file.exists():
        print(f"File not found: {ksy_file}")
        exit(1)

    # ensure output directory exists
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating markdown documentation for {ksy_file}")
    main(ksy_file, output_dir)
