import typing, abc
from System.Collections.Generic import List_1
from System.IO import BinaryReader, BinaryWriter, Stream
from LibRun8.Common import Vector3, TileIndex, DispatcherLight, Rectangle, Vector2, ModelObject, Matrix, Vector4, SignalHead, SceneryAssetLoader, TrackSection, LightLoader
from System import Array_1

class AISignalDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Signals(self) -> List_1[AISignalDatabase.AISignal]: ...
    @Signals.setter
    def Signals(self, value: List_1[AISignalDatabase.AISignal]) -> List_1[AISignalDatabase.AISignal]: ...
    @staticmethod
    def Read(path: str) -> AISignalDatabase: ...
    def Write(self, path: str) -> None: ...

    class AISignal:
        def __init__(self) -> None: ...
        @property
        def Bool0(self) -> bool: ...
        @Bool0.setter
        def Bool0(self, value: bool) -> bool: ...
        @property
        def Class336_0(self) -> AISignalDatabase.Class336: ...
        @Class336_0.setter
        def Class336_0(self, value: AISignalDatabase.Class336) -> AISignalDatabase.Class336: ...
        @property
        def Class336_1(self) -> AISignalDatabase.Class336: ...
        @Class336_1.setter
        def Class336_1(self, value: AISignalDatabase.Class336) -> AISignalDatabase.Class336: ...
        @property
        def Int0(self) -> int: ...
        @Int0.setter
        def Int0(self, value: int) -> int: ...
        @property
        def Int1(self) -> int: ...
        @Int1.setter
        def Int1(self, value: int) -> int: ...
        @property
        def SignalIndices(self) -> List_1[int]: ...
        @SignalIndices.setter
        def SignalIndices(self, value: List_1[int]) -> List_1[int]: ...
        @staticmethod
        def Read(reader: BinaryReader) -> AISignalDatabase.AISignal: ...


    class Class336:
        def __init__(self) -> None: ...
        @property
        def Int0(self) -> int: ...
        @Int0.setter
        def Int0(self, value: int) -> int: ...
        @property
        def Int1(self) -> int: ...
        @Int1.setter
        def Int1(self, value: int) -> int: ...
        @staticmethod
        def Read(reader: BinaryReader) -> AISignalDatabase.Class336: ...



class AITrackSpeedDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def TrackSpeeds(self) -> List_1[AITrackSpeedDatabase.TrackSpeed]: ...
    @TrackSpeeds.setter
    def TrackSpeeds(self, value: List_1[AITrackSpeedDatabase.TrackSpeed]) -> List_1[AITrackSpeedDatabase.TrackSpeed]: ...
    @staticmethod
    def Read(path: str) -> AITrackSpeedDatabase: ...
    def Write(self, path: str) -> None: ...

    class TrackSpeed:
        def __init__(self) -> None: ...
        @property
        def Int0(self) -> int: ...
        @Int0.setter
        def Int0(self, value: int) -> int: ...
        @property
        def Speeds(self) -> List_1[AITrackSpeedDatabase.TrackSpeedEntry]: ...
        @Speeds.setter
        def Speeds(self, value: List_1[AITrackSpeedDatabase.TrackSpeedEntry]) -> List_1[AITrackSpeedDatabase.TrackSpeedEntry]: ...
        @staticmethod
        def Read(reader: BinaryReader) -> AITrackSpeedDatabase.TrackSpeed: ...


    class TrackSpeedEntry:
        def __init__(self) -> None: ...
        @property
        def Int0(self) -> int: ...
        @Int0.setter
        def Int0(self, value: int) -> int: ...
        @property
        def Int1(self) -> int: ...
        @Int1.setter
        def Int1(self, value: int) -> int: ...
        @property
        def Int2(self) -> int: ...
        @Int2.setter
        def Int2(self, value: int) -> int: ...
        @staticmethod
        def Read(reader: BinaryReader) -> AITrackSpeedDatabase.TrackSpeedEntry: ...



class BlockDetectorDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Detectors(self) -> List_1[BlockDetectorDatabase.BlockDetector]: ...
    @Detectors.setter
    def Detectors(self, value: List_1[BlockDetectorDatabase.BlockDetector]) -> List_1[BlockDetectorDatabase.BlockDetector]: ...
    @staticmethod
    def Read(path: str) -> BlockDetectorDatabase: ...
    def Write(self, path: str) -> None: ...

    class BlockDetector:
        def __init__(self) -> None: ...
        @property
        def Index(self) -> int: ...
        @Index.setter
        def Index(self, value: int) -> int: ...
        @property
        def PositionXYZ(self) -> Vector3: ...
        @PositionXYZ.setter
        def PositionXYZ(self, value: Vector3) -> Vector3: ...
        @property
        def TileXZ(self) -> TileIndex: ...
        @TileXZ.setter
        def TileXZ(self, value: TileIndex) -> TileIndex: ...
        @property
        def Tracks(self) -> List_1[int]: ...
        @Tracks.setter
        def Tracks(self, value: List_1[int]) -> List_1[int]: ...
        @staticmethod
        def Read(reader: BinaryReader) -> BlockDetectorDatabase.BlockDetector: ...



class CarSpewerDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Spewers(self) -> List_1[CarSpewerDatabase.CarSpewer]: ...
    @Spewers.setter
    def Spewers(self, value: List_1[CarSpewerDatabase.CarSpewer]) -> List_1[CarSpewerDatabase.CarSpewer]: ...
    @staticmethod
    def Read(path: str) -> CarSpewerDatabase: ...
    def Write(self, path: str) -> None: ...

    class CarSpewer:
        def __init__(self) -> None: ...
        @property
        def CarSpewStartPoints(self) -> List_1[CarSpewerDatabase.CarSpewStartPoint]: ...
        @CarSpewStartPoints.setter
        def CarSpewStartPoints(self, value: List_1[CarSpewerDatabase.CarSpewStartPoint]) -> List_1[CarSpewerDatabase.CarSpewStartPoint]: ...
        @property
        def Int0(self) -> int: ...
        @Int0.setter
        def Int0(self, value: int) -> int: ...
        @property
        def MaxNumCars(self) -> int: ...
        @MaxNumCars.setter
        def MaxNumCars(self, value: int) -> int: ...
        @property
        def MaxSpeed(self) -> float: ...
        @MaxSpeed.setter
        def MaxSpeed(self, value: float) -> float: ...
        @property
        def MaxTimeBetwixtSpew(self) -> float: ...
        @MaxTimeBetwixtSpew.setter
        def MaxTimeBetwixtSpew(self, value: float) -> float: ...
        @property
        def MinTimeBetwixtSpew(self) -> float: ...
        @MinTimeBetwixtSpew.setter
        def MinTimeBetwixtSpew(self, value: float) -> float: ...
        @property
        def RoadNodeIndex(self) -> int: ...
        @RoadNodeIndex.setter
        def RoadNodeIndex(self, value: int) -> int: ...
        @staticmethod
        def Read(reader: BinaryReader) -> CarSpewerDatabase.CarSpewer: ...


    class CarSpewStartPoint:
        def __init__(self) -> None: ...
        @property
        def Heading(self) -> float: ...
        @Heading.setter
        def Heading(self, value: float) -> float: ...
        @property
        def PosXYZ(self) -> Vector3: ...
        @PosXYZ.setter
        def PosXYZ(self, value: Vector3) -> Vector3: ...
        @property
        def TileXZ(self) -> TileIndex: ...
        @TileXZ.setter
        def TileXZ(self, value: TileIndex) -> TileIndex: ...
        @staticmethod
        def Read(reader: BinaryReader) -> CarSpewerDatabase.CarSpewStartPoint: ...



class CommTowerDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def CommTowers(self) -> List_1[CommTowerDatabase.CommTower]: ...
    @CommTowers.setter
    def CommTowers(self, value: List_1[CommTowerDatabase.CommTower]) -> List_1[CommTowerDatabase.CommTower]: ...
    @staticmethod
    def Read(path: str) -> CommTowerDatabase: ...
    def Write(self, path: str) -> None: ...

    class CommTower:
        def __init__(self) -> None: ...
        @property
        def Channel(self) -> int: ...
        @Channel.setter
        def Channel(self, value: int) -> int: ...
        @property
        def DispDMTFCode(self) -> str: ...
        @DispDMTFCode.setter
        def DispDMTFCode(self, value: str) -> str: ...
        @property
        def DispToneCueName(self) -> str: ...
        @DispToneCueName.setter
        def DispToneCueName(self, value: str) -> str: ...
        @property
        def EmgDMTFCode(self) -> str: ...
        @EmgDMTFCode.setter
        def EmgDMTFCode(self, value: str) -> str: ...
        @property
        def Position(self) -> Vector3: ...
        @Position.setter
        def Position(self, value: Vector3) -> Vector3: ...
        @property
        def RangeMeters(self) -> float: ...
        @RangeMeters.setter
        def RangeMeters(self, value: float) -> float: ...
        @property
        def TileXZ(self) -> TileIndex: ...
        @TileXZ.setter
        def TileXZ(self, value: TileIndex) -> TileIndex: ...
        @property
        def TowerID(self) -> str: ...
        @TowerID.setter
        def TowerID(self, value: str) -> str: ...
        @staticmethod
        def Read(reader: BinaryReader) -> CommTowerDatabase.CommTower: ...
        def Write(self, writer: BinaryWriter) -> None: ...



class DefectDetector:
    def __init__(self) -> None: ...
    @property
    def DraggingEquipment(self) -> bool: ...
    @DraggingEquipment.setter
    def DraggingEquipment(self, value: bool) -> bool: ...
    @property
    def HiWide(self) -> bool: ...
    @HiWide.setter
    def HiWide(self, value: bool) -> bool: ...
    @property
    def Hotbox(self) -> bool: ...
    @Hotbox.setter
    def Hotbox(self, value: bool) -> bool: ...
    @property
    def IsAEI(self) -> typing.Optional[bool]: ...
    @IsAEI.setter
    def IsAEI(self, value: typing.Optional[bool]) -> typing.Optional[bool]: ...
    @property
    def Milepost(self) -> int: ...
    @Milepost.setter
    def Milepost(self, value: int) -> int: ...
    @property
    def MilepostDecimal(self) -> int: ...
    @MilepostDecimal.setter
    def MilepostDecimal(self, value: int) -> int: ...
    @property
    def PositionXYZ(self) -> Vector3: ...
    @PositionXYZ.setter
    def PositionXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def SoundBankName(self) -> str: ...
    @SoundBankName.setter
    def SoundBankName(self, value: str) -> str: ...
    @property
    def SquawkOnDefectOnly(self) -> bool: ...
    @SquawkOnDefectOnly.setter
    def SquawkOnDefectOnly(self, value: bool) -> bool: ...
    @property
    def SquawkTemperature(self) -> bool: ...
    @SquawkTemperature.setter
    def SquawkTemperature(self, value: bool) -> bool: ...
    @property
    def SquawkTrainSpeed(self) -> bool: ...
    @SquawkTrainSpeed.setter
    def SquawkTrainSpeed(self, value: bool) -> bool: ...
    @property
    def TileXZ(self) -> TileIndex: ...
    @TileXZ.setter
    def TileXZ(self, value: TileIndex) -> TileIndex: ...
    @property
    def TrackNumber(self) -> int: ...
    @TrackNumber.setter
    def TrackNumber(self, value: int) -> int: ...
    @property
    def Version(self) -> int: ...
    @Version.setter
    def Version(self, value: int) -> int: ...
    @property
    def WaveBankName(self) -> str: ...
    @WaveBankName.setter
    def WaveBankName(self, value: str) -> str: ...
    @staticmethod
    def Read(reader: BinaryReader) -> DefectDetector: ...


class DefectDetectorList(FileFormat):
    def __init__(self) -> None: ...
    @property
    def DefectDetectors(self) -> List_1[DefectDetector]: ...
    @DefectDetectors.setter
    def DefectDetectors(self, value: List_1[DefectDetector]) -> List_1[DefectDetector]: ...
    @staticmethod
    def Read(path: str) -> DefectDetectorList: ...
    def Write(self, path: str) -> None: ...


class DispatcherLightBlockDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def DispatchLights(self) -> List_1[DispatcherLight]: ...
    @DispatchLights.setter
    def DispatchLights(self, value: List_1[DispatcherLight]) -> List_1[DispatcherLight]: ...
    @staticmethod
    def Read(path: str) -> DispatcherLightBlockDatabase: ...
    def Write(self, path: str) -> None: ...


class DispatcherSignalControllerDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Controllers(self) -> List_1[DispatcherSignalControllerDatabase.DispatcherSignalController]: ...
    @Controllers.setter
    def Controllers(self, value: List_1[DispatcherSignalControllerDatabase.DispatcherSignalController]) -> List_1[DispatcherSignalControllerDatabase.DispatcherSignalController]: ...
    @staticmethod
    def Read(path: str) -> DispatcherSignalControllerDatabase: ...
    def Write(self, path: str) -> None: ...

    class DispatcherSignalController:
        def __init__(self) -> None: ...
        @property
        def Button(self) -> DispatcherLight: ...
        @Button.setter
        def Button(self, value: DispatcherLight) -> DispatcherLight: ...
        @property
        def Signals(self) -> List_1[int]: ...
        @Signals.setter
        def Signals(self, value: List_1[int]) -> List_1[int]: ...
        @property
        def String0(self) -> str: ...
        @String0.setter
        def String0(self, value: str) -> str: ...
        @staticmethod
        def Read(reader: BinaryReader) -> DispatcherSignalControllerDatabase.DispatcherSignalController: ...



class DispatcherSwitchIconDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Buttons(self) -> List_1[DispatcherSwitchIconDatabase.DispatcherButton]: ...
    @Buttons.setter
    def Buttons(self, value: List_1[DispatcherSwitchIconDatabase.DispatcherButton]) -> List_1[DispatcherSwitchIconDatabase.DispatcherButton]: ...
    @staticmethod
    def Read(path: str) -> DispatcherSwitchIconDatabase: ...
    def Write(self, path: str) -> None: ...

    class DispatcherButton:
        def __init__(self) -> None: ...
        @property
        def Button(self) -> Rectangle: ...
        @Button.setter
        def Button(self, value: Rectangle) -> Rectangle: ...
        @property
        def Index(self) -> int: ...
        @Index.setter
        def Index(self, value: int) -> int: ...
        @property
        def RoutePrefix(self) -> int: ...
        @RoutePrefix.setter
        def RoutePrefix(self, value: int) -> int: ...
        @property
        def ScreenXY(self) -> Vector2: ...
        @ScreenXY.setter
        def ScreenXY(self, value: Vector2) -> Vector2: ...
        @property
        def String0(self) -> str: ...
        @String0.setter
        def String0(self, value: str) -> str: ...
        @property
        def SwitchControllers(self) -> List_1[int]: ...
        @SwitchControllers.setter
        def SwitchControllers(self, value: List_1[int]) -> List_1[int]: ...
        @staticmethod
        def Read(reader: BinaryReader) -> DispatcherSwitchIconDatabase.DispatcherButton: ...



class FileFormat(abc.ABC):
    @abc.abstractmethod
    def Write(self, path: str) -> None: ...


class GateRotationType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    Vertical : GateRotationType # 0
    Horizontal : GateRotationType # 1
    XBuckNoBell : GateRotationType # 2


class HumpConfigDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Humps(self) -> List_1[HumpConfigDatabase.HumpConfigEntry]: ...
    @Humps.setter
    def Humps(self, value: List_1[HumpConfigDatabase.HumpConfigEntry]) -> List_1[HumpConfigDatabase.HumpConfigEntry]: ...
    @staticmethod
    def Read(path: str) -> HumpConfigDatabase: ...
    def Write(self, path: str) -> None: ...

    class HumpConfigEntry:
        def __init__(self) -> None: ...
        @property
        def Configs(self) -> List_1[HumpConfigDatabase.HumpConfigEntry.HumpConfig]: ...
        @Configs.setter
        def Configs(self, value: List_1[HumpConfigDatabase.HumpConfigEntry.HumpConfig]) -> List_1[HumpConfigDatabase.HumpConfigEntry.HumpConfig]: ...
        @property
        def Name(self) -> str: ...
        @Name.setter
        def Name(self, value: str) -> str: ...
        @staticmethod
        def Read(reader: BinaryReader) -> HumpConfigDatabase.HumpConfigEntry: ...

        class HumpConfig:
            def __init__(self) -> None: ...
            @property
            def ConfigName(self) -> str: ...
            @ConfigName.setter
            def ConfigName(self, value: str) -> str: ...
            @property
            def Tracks(self) -> List_1[HumpConfigDatabase.HumpConfigEntry.HumpConfig.HumpConfigTrack]: ...
            @Tracks.setter
            def Tracks(self, value: List_1[HumpConfigDatabase.HumpConfigEntry.HumpConfig.HumpConfigTrack]) -> List_1[HumpConfigDatabase.HumpConfigEntry.HumpConfig.HumpConfigTrack]: ...
            @staticmethod
            def Read(reader: BinaryReader) -> HumpConfigDatabase.HumpConfigEntry.HumpConfig: ...

            class HumpConfigTrack:
                def __init__(self) -> None: ...
                @property
                def Tags(self) -> List_1[str]: ...
                @Tags.setter
                def Tags(self, value: List_1[str]) -> List_1[str]: ...
                @property
                def TrackName(self) -> str: ...
                @TrackName.setter
                def TrackName(self, value: str) -> str: ...
                @staticmethod
                def Read(reader: BinaryReader) -> HumpConfigDatabase.HumpConfigEntry.HumpConfig.HumpConfigTrack: ...





class HumpControllerList(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Controllers(self) -> List_1[HumpControllerList.HumpController]: ...
    @Controllers.setter
    def Controllers(self, value: List_1[HumpControllerList.HumpController]) -> List_1[HumpControllerList.HumpController]: ...
    @staticmethod
    def Read(path: str) -> HumpControllerList: ...
    def Write(self, path: str) -> None: ...

    class HumpController:
        def __init__(self) -> None: ...
        @property
        def Name(self) -> str: ...
        @Name.setter
        def Name(self, value: str) -> str: ...
        @property
        def Position(self) -> Vector3: ...
        @Position.setter
        def Position(self, value: Vector3) -> Vector3: ...
        @property
        def TileXZ(self) -> TileIndex: ...
        @TileXZ.setter
        def TileXZ(self, value: TileIndex) -> TileIndex: ...
        @property
        def TrackPaths(self) -> List_1[HumpControllerList.HumpController.TrackPath]: ...
        @TrackPaths.setter
        def TrackPaths(self, value: List_1[HumpControllerList.HumpController.TrackPath]) -> List_1[HumpControllerList.HumpController.TrackPath]: ...
        @staticmethod
        def Read(reader: BinaryReader) -> HumpControllerList.HumpController: ...

        class TrackPath:
            def __init__(self) -> None: ...
            @property
            def SwitchList(self) -> List_1[HumpControllerList.HumpController.TrackPath.SwitchConnection]: ...
            @SwitchList.setter
            def SwitchList(self, value: List_1[HumpControllerList.HumpController.TrackPath.SwitchConnection]) -> List_1[HumpControllerList.HumpController.TrackPath.SwitchConnection]: ...
            @property
            def TrackName(self) -> str: ...
            @TrackName.setter
            def TrackName(self, value: str) -> str: ...
            @staticmethod
            def Read(reader: BinaryReader) -> HumpControllerList.HumpController.TrackPath: ...

            class SwitchConnection:
                def __init__(self) -> None: ...
                @property
                def IsReversed(self) -> bool: ...
                @IsReversed.setter
                def IsReversed(self, value: bool) -> bool: ...
                @property
                def TrackSectionIndex(self) -> int: ...
                @TrackSectionIndex.setter
                def TrackSectionIndex(self, value: int) -> int: ...
                @staticmethod
                def Read(reader: BinaryReader) -> HumpControllerList.HumpController.TrackPath.SwitchConnection: ...





class Model(FileFormat):
    def __init__(self) -> None: ...
    fileName : str
    @property
    def BoundingRadius(self) -> float: ...
    @BoundingRadius.setter
    def BoundingRadius(self, value: float) -> float: ...
    @property
    def IsAdvancedModel(self) -> bool: ...
    @IsAdvancedModel.setter
    def IsAdvancedModel(self, value: bool) -> bool: ...
    @property
    def ObjectCount(self) -> int: ...
    @ObjectCount.setter
    def ObjectCount(self, value: int) -> int: ...
    @property
    def Objects(self) -> List_1[ModelObject]: ...
    @Objects.setter
    def Objects(self, value: List_1[ModelObject]) -> List_1[ModelObject]: ...
    @property
    def UnkMatrix(self) -> Matrix: ...
    @UnkMatrix.setter
    def UnkMatrix(self, value: Matrix) -> Matrix: ...
    @property
    def UnkVec3(self) -> Vector3: ...
    @UnkVec3.setter
    def UnkVec3(self, value: Vector3) -> Vector3: ...
    def ReadGLTF(self, path: str) -> None: ...
    def Write(self, path: str) -> None: ...
    def WriteGLTF(self, path: str) -> None: ...
    # Skipped Read due to it being static, abstract and generic.

    Read : Read_MethodGroup
    class Read_MethodGroup:
        @typing.overload
        def __call__(self, path: str) -> Model:...
        @typing.overload
        def __call__(self, stream: Stream) -> Model:...



class RoadDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Sections(self) -> List_1[RoadDatabase.RoadSection]: ...
    @Sections.setter
    def Sections(self, value: List_1[RoadDatabase.RoadSection]) -> List_1[RoadDatabase.RoadSection]: ...
    @staticmethod
    def Read(path: str) -> RoadDatabase: ...
    def Write(self, path: str) -> None: ...

    class RoadExtrusionType(typing.SupportsInt):
        @typing.overload
        def __init__(self, value : int) -> None: ...
        @typing.overload
        def __init__(self, value : int, force_if_true: bool) -> None: ...
        def __int__(self) -> int: ...
        
        # Values:
        const_0 : RoadDatabase.RoadExtrusionType # 0
        const_1 : RoadDatabase.RoadExtrusionType # 1
        const_2 : RoadDatabase.RoadExtrusionType # 2
        const_3 : RoadDatabase.RoadExtrusionType # 3
        const_4 : RoadDatabase.RoadExtrusionType # 4
        const_5 : RoadDatabase.RoadExtrusionType # 5
        const_6 : RoadDatabase.RoadExtrusionType # 6
        const_7 : RoadDatabase.RoadExtrusionType # 7
        const_8 : RoadDatabase.RoadExtrusionType # 8
        const_9 : RoadDatabase.RoadExtrusionType # 9
        const_10 : RoadDatabase.RoadExtrusionType # 10
        const_11 : RoadDatabase.RoadExtrusionType # 11
        const_12 : RoadDatabase.RoadExtrusionType # 12
        const_13 : RoadDatabase.RoadExtrusionType # 13


    class RoadNode:
        def __init__(self) -> None: ...
        @property
        def ArcLengthMeters(self) -> float: ...
        @ArcLengthMeters.setter
        def ArcLengthMeters(self, value: float) -> float: ...
        @property
        def CurveSign(self) -> int: ...
        @CurveSign.setter
        def CurveSign(self, value: int) -> int: ...
        @property
        def Float0(self) -> float: ...
        @Float0.setter
        def Float0(self, value: float) -> float: ...
        @property
        def Float1(self) -> float: ...
        @Float1.setter
        def Float1(self, value: float) -> float: ...
        @property
        def Index(self) -> int: ...
        @Index.setter
        def Index(self, value: int) -> int: ...
        @property
        def Int3(self) -> int: ...
        @Int3.setter
        def Int3(self, value: int) -> int: ...
        @property
        def MaxSpeedMPH(self) -> float: ...
        @MaxSpeedMPH.setter
        def MaxSpeedMPH(self, value: float) -> float: ...
        @property
        def NumSegments(self) -> int: ...
        @NumSegments.setter
        def NumSegments(self, value: int) -> int: ...
        @property
        def PositionXYZ(self) -> Vector3: ...
        @PositionXYZ.setter
        def PositionXYZ(self, value: Vector3) -> Vector3: ...
        @property
        def TangentXYZ(self) -> Vector3: ...
        @TangentXYZ.setter
        def TangentXYZ(self, value: Vector3) -> Vector3: ...
        @property
        def TileXZ(self) -> TileIndex: ...
        @TileXZ.setter
        def TileXZ(self, value: TileIndex) -> TileIndex: ...
        @staticmethod
        def Read(reader: BinaryReader) -> RoadDatabase.RoadNode: ...


    class RoadSection:
        def __init__(self) -> None: ...
        @property
        def ArcLengthMeters(self) -> float: ...
        @ArcLengthMeters.setter
        def ArcLengthMeters(self, value: float) -> float: ...
        @property
        def Int0(self) -> int: ...
        @Int0.setter
        def Int0(self, value: int) -> int: ...
        @property
        def Int1(self) -> int: ...
        @Int1.setter
        def Int1(self, value: int) -> int: ...
        @property
        def LaneCenterOffsetMeters(self) -> float: ...
        @LaneCenterOffsetMeters.setter
        def LaneCenterOffsetMeters(self, value: float) -> float: ...
        @property
        def LaneSpacingMeters(self) -> float: ...
        @LaneSpacingMeters.setter
        def LaneSpacingMeters(self, value: float) -> float: ...
        @property
        def Nodes(self) -> List_1[RoadDatabase.RoadNode]: ...
        @Nodes.setter
        def Nodes(self, value: List_1[RoadDatabase.RoadNode]) -> List_1[RoadDatabase.RoadNode]: ...
        @property
        def NumLanesPerSide(self) -> int: ...
        @NumLanesPerSide.setter
        def NumLanesPerSide(self, value: int) -> int: ...
        @property
        def Type(self) -> RoadDatabase.RoadExtrusionType: ...
        @Type.setter
        def Type(self, value: RoadDatabase.RoadExtrusionType) -> RoadDatabase.RoadExtrusionType: ...
        @staticmethod
        def Read(reader: BinaryReader) -> RoadDatabase.RoadSection: ...



class Signal(FileFormat):
    def __init__(self) -> None: ...
    @property
    def B0(self) -> bool: ...
    @B0.setter
    def B0(self, value: bool) -> bool: ...
    @property
    def IsDwarf(self) -> bool: ...
    @IsDwarf.setter
    def IsDwarf(self, value: bool) -> bool: ...
    @property
    def LeastRestrictiveSignalState(self) -> int: ...
    @LeastRestrictiveSignalState.setter
    def LeastRestrictiveSignalState(self, value: int) -> int: ...
    @property
    def ModelName(self) -> str: ...
    @ModelName.setter
    def ModelName(self, value: str) -> str: ...
    @property
    def SignalLights(self) -> typing.List[Signal.SignalLight]: ...
    @SignalLights.setter
    def SignalLights(self, value: typing.List[Signal.SignalLight]) -> typing.List[Signal.SignalLight]: ...
    @staticmethod
    def Read(path: str) -> Signal: ...
    def Write(self, path: str) -> None: ...

    class SignalLight:
        def __init__(self) -> None: ...
        @property
        def Color(self) -> Vector4: ...
        @Color.setter
        def Color(self, value: Vector4) -> Vector4: ...
        @property
        def GlareList(self) -> typing.List[Vector3]: ...
        @GlareList.setter
        def GlareList(self, value: typing.List[Vector3]) -> typing.List[Vector3]: ...
        @property
        def IsLimitedYardLight(self) -> bool: ...
        @IsLimitedYardLight.setter
        def IsLimitedYardLight(self, value: bool) -> bool: ...
        @property
        def lightDirectionDeg(self) -> Vector3: ...
        @lightDirectionDeg.setter
        def lightDirectionDeg(self, value: Vector3) -> Vector3: ...
        @property
        def LightGlareRadiusMeters(self) -> float: ...
        @LightGlareRadiusMeters.setter
        def LightGlareRadiusMeters(self, value: float) -> float: ...
        @property
        def LightIntensity(self) -> float: ...
        @LightIntensity.setter
        def LightIntensity(self, value: float) -> float: ...
        @property
        def LightOffset(self) -> Vector3: ...
        @LightOffset.setter
        def LightOffset(self, value: Vector3) -> Vector3: ...
        @property
        def LightRange(self) -> float: ...
        @LightRange.setter
        def LightRange(self, value: float) -> float: ...



class SignalHeadDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def SignalHeads(self) -> List_1[SignalHead]: ...
    @SignalHeads.setter
    def SignalHeads(self, value: List_1[SignalHead]) -> List_1[SignalHead]: ...
    @staticmethod
    def Read(path: str) -> SignalHeadDatabase: ...
    def Write(self, path: str) -> None: ...


class Stars4(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Entries(self) -> typing.List[str]: ...
    @Entries.setter
    def Entries(self, value: typing.List[str]) -> typing.List[str]: ...
    @staticmethod
    def Read(path: str) -> Stars4: ...
    def Write(self, path: str) -> None: ...


class TileScenery(FileFormat):
    def __init__(self) -> None: ...
    LoadList : List_1[SceneryAssetLoader]
    @staticmethod
    def Read(path: str) -> TileScenery: ...
    def Write(self, path: str) -> None: ...


class TrackDatabase(FileFormat):
    def __init__(self) -> None: ...
    @property
    def Sections(self) -> typing.List[TrackSection]: ...
    @Sections.setter
    def Sections(self, value: typing.List[TrackSection]) -> typing.List[TrackSection]: ...
    @staticmethod
    def Read(path: str) -> TrackDatabase: ...
    def Write(self, path: str) -> None: ...


class XNG(FileFormat):
    def __init__(self) -> None: ...
    @property
    def ActiveDegrees(self) -> float: ...
    @ActiveDegrees.setter
    def ActiveDegrees(self, value: float) -> float: ...
    @property
    def GateModelName(self) -> str: ...
    @GateModelName.setter
    def GateModelName(self, value: str) -> str: ...
    @property
    def GateOffset(self) -> Vector3: ...
    @GateOffset.setter
    def GateOffset(self, value: Vector3) -> Vector3: ...
    @property
    def GateRotationType(self) -> GateRotationType: ...
    @GateRotationType.setter
    def GateRotationType(self, value: GateRotationType) -> GateRotationType: ...
    @property
    def InactiveDegrees(self) -> float: ...
    @InactiveDegrees.setter
    def InactiveDegrees(self, value: float) -> float: ...
    @property
    def Lights(self) -> typing.List[LightLoader]: ...
    @Lights.setter
    def Lights(self, value: typing.List[LightLoader]) -> typing.List[LightLoader]: ...
    @property
    def RotationDegreesPerSecond(self) -> float: ...
    @RotationDegreesPerSecond.setter
    def RotationDegreesPerSecond(self, value: float) -> float: ...
    @property
    def StandModelName(self) -> str: ...
    @StandModelName.setter
    def StandModelName(self, value: str) -> str: ...
    @staticmethod
    def Read(path: str) -> XNG: ...
    def Write(self, path: str) -> None: ...

    class SignalLight:
        def __init__(self) -> None: ...
        @property
        def Color(self) -> Vector4: ...
        @Color.setter
        def Color(self, value: Vector4) -> Vector4: ...
        @property
        def GlareList(self) -> typing.List[Vector3]: ...
        @GlareList.setter
        def GlareList(self, value: typing.List[Vector3]) -> typing.List[Vector3]: ...
        @property
        def LightGlareRadiusMeters(self) -> float: ...
        @LightGlareRadiusMeters.setter
        def LightGlareRadiusMeters(self, value: float) -> float: ...
        @property
        def LightOffset(self) -> Vector3: ...
        @LightOffset.setter
        def LightOffset(self, value: Vector3) -> Vector3: ...
        @property
        def LightRange(self) -> float: ...
        @LightRange.setter
        def LightRange(self, value: float) -> float: ...


