<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="morelinq" Version="4.2.0" />
    <PackageReference Include="SharpGLTF.Core" Version="1.0.5" />
    <PackageReference Include="SharpGLTF.Runtime" Version="1.0.5" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.5" />
  </ItemGroup>

</Project>
