import typing, abc
from System import Array_1
from System.IO import FileInfo, BinaryReader
from LibRun8.Common import VertexStruct
from LibRun8.Formats.Terrain import TerrainTileLoadData, TerrainTile
from System.Collections.Generic import List_1

class R8String:
    def __init__(self) -> None: ...
    @staticmethod
    def DecodeBytes(bytes: typing.List[int]) -> str: ...
    @staticmethod
    def EncodeBytes(val: str) -> typing.List[int]: ...


class Texture:
    def __init__(self) -> None: ...
    @staticmethod
    def Decrypt(file: FileInfo) -> None: ...
    @staticmethod
    def Encrypt(file: FileInfo) -> None: ...


class TileUtil:
    def __init__(self) -> None: ...
    @staticmethod
    def CalculateNormals(vertices: typing.List[VertexStruct]) -> None: ...
    @staticmethod
    def LoadTextures(reader: BinaryReader, terrainTileLoadData: TerrainTileLoadData, bool0: bool) -> None: ...
    @staticmethod
    def SetUpChunkIndices(numHixels: int, vertCounter: int, indices: List_1[int]) -> None: ...
    @staticmethod
    def smethod_13(tile: TerrainTile) -> None: ...


class Utils(abc.ABC):
    @staticmethod
    def Clamp(value: int, min: int, max: int) -> int: ...
    @staticmethod
    def CompareByteArrays(arr1: typing.List[int], arr2: typing.List[int]) -> bool: ...
    @staticmethod
    def ComputeMD5ForBytes(data: typing.List[int]) -> typing.List[int]: ...
    @staticmethod
    def DegreesToRadians(degree: float) -> float: ...
    @staticmethod
    def IsZero(a: float) -> bool: ...
    @staticmethod
    def Lerp(from_: float, to: float, amount: float) -> float: ...
    @staticmethod
    def NearEqual(a: float, b: float) -> bool: ...
    @staticmethod
    def smethod_0(int_0: int, int_1: int, int_2: int, list_1: List_1[VertexStruct]) -> None: ...
    # Skipped ConvertToJaggedArray due to it being static, abstract and generic.

    ConvertToJaggedArray : ConvertToJaggedArray_MethodGroup
    class ConvertToJaggedArray_MethodGroup:
        def __getitem__(self, t:typing.Type[ConvertToJaggedArray_1_T1]) -> ConvertToJaggedArray_1[ConvertToJaggedArray_1_T1]: ...

        ConvertToJaggedArray_1_T1 = typing.TypeVar('ConvertToJaggedArray_1_T1')
        class ConvertToJaggedArray_1(typing.Generic[ConvertToJaggedArray_1_T1]):
            ConvertToJaggedArray_1_T = Utils.ConvertToJaggedArray_MethodGroup.ConvertToJaggedArray_1_T1
            def __call__(self, twoDArray: typing.List[ConvertToJaggedArray_1_T]) -> typing.List[typing.List[ConvertToJaggedArray_1_T]]:...



