import typing, clr
from System import Array_1, IFormattable, IFormatProvider
from System.Collections.Generic import List_1
from System.IO import BinaryReader
from LibRun8.Formats import Model

class Class252:
    def __init__(self) -> None: ...
    @property
    def quaternion_0(self) -> typing.List[Quaternion]: ...
    @quaternion_0.setter
    def quaternion_0(self, value: typing.List[Quaternion]) -> typing.List[Quaternion]: ...
    @property
    def quaternion_1(self) -> Quaternion: ...
    @quaternion_1.setter
    def quaternion_1(self, value: Quaternion) -> Quaternion: ...
    @property
    def vector3_0(self) -> typing.List[Vector3]: ...
    @vector3_0.setter
    def vector3_0(self, value: typing.List[Vector3]) -> typing.List[Vector3]: ...
    @property
    def vector3_1(self) -> Vector3: ...
    @vector3_1.setter
    def vector3_1(self, value: Vector3) -> Vector3: ...


class DecalLoader:
    def __init__(self) -> None: ...
    @property
    def ColorRGB(self) -> Vector3: ...
    @ColorRGB.setter
    def ColorRGB(self, value: Vector3) -> Vector3: ...
    @property
    def Digits(self) -> List_1[int]: ...
    @Digits.setter
    def Digits(self, value: List_1[int]) -> List_1[int]: ...
    @property
    def IsGaugeNeedle(self) -> bool: ...
    @IsGaugeNeedle.setter
    def IsGaugeNeedle(self, value: bool) -> bool: ...
    @property
    def OffsetXYZ(self) -> Vector3: ...
    @OffsetXYZ.setter
    def OffsetXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def RotationDegXYZ(self) -> Vector3: ...
    @RotationDegXYZ.setter
    def RotationDegXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def Size(self) -> float: ...
    @Size.setter
    def Size(self, value: float) -> float: ...
    @property
    def TextureName(self) -> str: ...
    @TextureName.setter
    def TextureName(self, value: str) -> str: ...


class DispatcherLight:
    def __init__(self) -> None: ...
    @property
    def ButtonRectangle(self) -> Rectangle: ...
    @ButtonRectangle.setter
    def ButtonRectangle(self, value: Rectangle) -> Rectangle: ...
    @property
    def Indices(self) -> List_1[int]: ...
    @Indices.setter
    def Indices(self, value: List_1[int]) -> List_1[int]: ...
    @property
    def ScreenXY(self) -> Vector2: ...
    @ScreenXY.setter
    def ScreenXY(self, value: Vector2) -> Vector2: ...
    @property
    def String0(self) -> str: ...
    @String0.setter
    def String0(self, value: str) -> str: ...
    @staticmethod
    def Read(reader: BinaryReader) -> DispatcherLight: ...


class Enum61(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    const_0 : Enum61 # 0
    const_1 : Enum61 # 1
    const_2 : Enum61 # 2
    const_3 : Enum61 # 3
    const_4 : Enum61 # 4


class Int4:
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @typing.overload
    def __init__(self, x: int, y: int, z: int, w: int) -> None: ...
    @property
    def W(self) -> int: ...
    @W.setter
    def W(self, value: int) -> int: ...
    @property
    def X(self) -> int: ...
    @X.setter
    def X(self, value: int) -> int: ...
    @property
    def Y(self) -> int: ...
    @Y.setter
    def Y(self, value: int) -> int: ...
    @property
    def Z(self) -> int: ...
    @Z.setter
    def Z(self, value: int) -> int: ...


class LightLoader:
    def __init__(self) -> None: ...
    @property
    def billboardGlare(self) -> bool: ...
    @billboardGlare.setter
    def billboardGlare(self, value: bool) -> bool: ...
    @property
    def Color(self) -> Vector4: ...
    @Color.setter
    def Color(self, value: Vector4) -> Vector4: ...
    @property
    def dayNiteSensorAmbientLevel(self) -> float: ...
    @dayNiteSensorAmbientLevel.setter
    def dayNiteSensorAmbientLevel(self, value: float) -> float: ...
    @property
    def decayExponent(self) -> float: ...
    @decayExponent.setter
    def decayExponent(self, value: float) -> float: ...
    @property
    def flashing(self) -> bool: ...
    @flashing.setter
    def flashing(self, value: bool) -> bool: ...
    @property
    def flashTimeRandomVariation(self) -> float: ...
    @flashTimeRandomVariation.setter
    def flashTimeRandomVariation(self, value: float) -> float: ...
    @property
    def flashTimerSeconds(self) -> float: ...
    @flashTimerSeconds.setter
    def flashTimerSeconds(self, value: float) -> float: ...
    @property
    def GlareList(self) -> typing.List[Vector3]: ...
    @GlareList.setter
    def GlareList(self, value: typing.List[Vector3]) -> typing.List[Vector3]: ...
    @property
    def glowScalar(self) -> float: ...
    @glowScalar.setter
    def glowScalar(self, value: float) -> float: ...
    @property
    def hasDayNiteSensor(self) -> bool: ...
    @hasDayNiteSensor.setter
    def hasDayNiteSensor(self, value: bool) -> bool: ...
    @property
    def isHepPowered(self) -> bool: ...
    @isHepPowered.setter
    def isHepPowered(self, value: bool) -> bool: ...
    @property
    def isIncandescent(self) -> bool: ...
    @isIncandescent.setter
    def isIncandescent(self, value: bool) -> bool: ...
    @property
    def IsLimitedYardLight(self) -> bool: ...
    @IsLimitedYardLight.setter
    def IsLimitedYardLight(self, value: bool) -> bool: ...
    @property
    def isMarkerLight(self) -> bool: ...
    @isMarkerLight.setter
    def isMarkerLight(self, value: bool) -> bool: ...
    @property
    def isNumberboardLight(self) -> bool: ...
    @isNumberboardLight.setter
    def isNumberboardLight(self, value: bool) -> bool: ...
    @property
    def isSpotLight(self) -> bool: ...
    @isSpotLight.setter
    def isSpotLight(self, value: bool) -> bool: ...
    @property
    def LightDirectionDeg(self) -> Vector3: ...
    @LightDirectionDeg.setter
    def LightDirectionDeg(self, value: Vector3) -> Vector3: ...
    @property
    def LightGlareRadiusMeters(self) -> float: ...
    @LightGlareRadiusMeters.setter
    def LightGlareRadiusMeters(self, value: float) -> float: ...
    @property
    def LightIntensity(self) -> float: ...
    @LightIntensity.setter
    def LightIntensity(self, value: float) -> float: ...
    @property
    def LightOffsetXYZ(self) -> Vector3: ...
    @LightOffsetXYZ.setter
    def LightOffsetXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def LightRange(self) -> float: ...
    @LightRange.setter
    def LightRange(self, value: float) -> float: ...
    @property
    def lightWidth(self) -> float: ...
    @lightWidth.setter
    def lightWidth(self, value: float) -> float: ...
    @property
    def renderGlareOnly(self) -> bool: ...
    @renderGlareOnly.setter
    def renderGlareOnly(self, value: bool) -> bool: ...


class Matrix(IFormattable):
    @typing.overload
    def __init__(self, M11: float, M12: float, M13: float, M14: float, M21: float, M22: float, M23: float, M24: float, M31: float, M32: float, M33: float, M34: float, M41: float, M42: float, M43: float, M44: float) -> None: ...
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @typing.overload
    def __init__(self, values: typing.List[float]) -> None: ...
    Identity : Matrix
    M11 : float
    M12 : float
    M13 : float
    M14 : float
    M21 : float
    M22 : float
    M23 : float
    M24 : float
    M31 : float
    M32 : float
    M33 : float
    M34 : float
    M41 : float
    M42 : float
    M43 : float
    M44 : float
    SizeInBytes : int
    Zero : Matrix
    @property
    def Backward(self) -> Vector3: ...
    @Backward.setter
    def Backward(self, value: Vector3) -> Vector3: ...
    @property
    def Column1(self) -> Vector4: ...
    @Column1.setter
    def Column1(self, value: Vector4) -> Vector4: ...
    @property
    def Column2(self) -> Vector4: ...
    @Column2.setter
    def Column2(self, value: Vector4) -> Vector4: ...
    @property
    def Column3(self) -> Vector4: ...
    @Column3.setter
    def Column3(self, value: Vector4) -> Vector4: ...
    @property
    def Column4(self) -> Vector4: ...
    @Column4.setter
    def Column4(self, value: Vector4) -> Vector4: ...
    @property
    def Down(self) -> Vector3: ...
    @Down.setter
    def Down(self, value: Vector3) -> Vector3: ...
    @property
    def Forward(self) -> Vector3: ...
    @Forward.setter
    def Forward(self, value: Vector3) -> Vector3: ...
    @property
    def IsIdentity(self) -> bool: ...
    @property
    def Item(self) -> float: ...
    @Item.setter
    def Item(self, value: float) -> float: ...
    @property
    def Item(self) -> float: ...
    @Item.setter
    def Item(self, value: float) -> float: ...
    @property
    def Left(self) -> Vector3: ...
    @Left.setter
    def Left(self, value: Vector3) -> Vector3: ...
    @property
    def Right(self) -> Vector3: ...
    @Right.setter
    def Right(self, value: Vector3) -> Vector3: ...
    @property
    def Row1(self) -> Vector4: ...
    @Row1.setter
    def Row1(self, value: Vector4) -> Vector4: ...
    @property
    def Row2(self) -> Vector4: ...
    @Row2.setter
    def Row2(self, value: Vector4) -> Vector4: ...
    @property
    def Row3(self) -> Vector4: ...
    @Row3.setter
    def Row3(self, value: Vector4) -> Vector4: ...
    @property
    def Row4(self) -> Vector4: ...
    @Row4.setter
    def Row4(self, value: Vector4) -> Vector4: ...
    @property
    def ScaleVector(self) -> Vector3: ...
    @ScaleVector.setter
    def ScaleVector(self, value: Vector3) -> Vector3: ...
    @property
    def TranslationVector(self) -> Vector3: ...
    @TranslationVector.setter
    def TranslationVector(self, value: Vector3) -> Vector3: ...
    @property
    def Up(self) -> Vector3: ...
    @Up.setter
    def Up(self, value: Vector3) -> Vector3: ...
    def Determinant(self) -> float: ...
    def ExchangeColumns(self, firstColumn: int, secondColumn: int) -> None: ...
    def ExchangeRows(self, firstRow: int, secondRow: int) -> None: ...
    def GetHashCode(self) -> int: ...
    def __add__(self, left: Matrix, right: Matrix) -> Matrix: ...
    @typing.overload
    def __truediv__(self, left: Matrix, right: float) -> Matrix: ...
    @typing.overload
    def __truediv__(self, left: Matrix, right: Matrix) -> Matrix: ...
    @typing.overload
    def __mul__(self, left: float, right: Matrix) -> Matrix: ...
    @typing.overload
    def __mul__(self, left: Matrix, right: float) -> Matrix: ...
    @typing.overload
    def __mul__(self, left: Matrix, right: Matrix) -> Matrix: ...
    def __sub__(self, left: Matrix, right: Matrix) -> Matrix: ...
    def __neg__(self, value: Matrix) -> Matrix: ...
    def __pos__(self, value: Matrix) -> Matrix: ...
    def ToArray(self) -> typing.List[float]: ...
    # Skipped Add due to it being static, abstract and generic.

    Add : Add_MethodGroup
    class Add_MethodGroup:
        @typing.overload
        def __call__(self, left: Matrix, right: Matrix) -> Matrix:...
        @typing.overload
        def __call__(self, left: clr.Reference[Matrix], right: clr.Reference[Matrix], result: clr.Reference[Matrix]) -> None:...

    # Skipped Divide due to it being static, abstract and generic.

    Divide : Divide_MethodGroup
    class Divide_MethodGroup:
        @typing.overload
        def __call__(self, left: Matrix, right: float) -> Matrix:...
        @typing.overload
        def __call__(self, left: Matrix, right: Matrix) -> Matrix:...
        @typing.overload
        def __call__(self, left: clr.Reference[Matrix], right: float, result: clr.Reference[Matrix]) -> None:...
        @typing.overload
        def __call__(self, left: clr.Reference[Matrix], right: clr.Reference[Matrix], result: clr.Reference[Matrix]) -> None:...

    # Skipped Exponent due to it being static, abstract and generic.

    Exponent : Exponent_MethodGroup
    class Exponent_MethodGroup:
        @typing.overload
        def __call__(self, value: Matrix, exponent: int) -> Matrix:...
        @typing.overload
        def __call__(self, value: clr.Reference[Matrix], exponent: int, result: clr.Reference[Matrix]) -> None:...

    # Skipped Invert due to it being static, abstract and generic.

    Invert : Invert_MethodGroup
    class Invert_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, value: Matrix) -> Matrix:...
        @typing.overload
        def __call__(self, value: clr.Reference[Matrix], result: clr.Reference[Matrix]) -> None:...

    # Skipped Multiply due to it being static, abstract and generic.

    Multiply : Multiply_MethodGroup
    class Multiply_MethodGroup:
        @typing.overload
        def __call__(self, left: Matrix, right: float) -> Matrix:...
        @typing.overload
        def __call__(self, left: Matrix, right: Matrix) -> Matrix:...
        @typing.overload
        def __call__(self, left: clr.Reference[Matrix], right: float, result: clr.Reference[Matrix]) -> None:...
        @typing.overload
        def __call__(self, left: clr.Reference[Matrix], right: clr.Reference[Matrix], result: clr.Reference[Matrix]) -> None:...

    # Skipped Negate due to it being static, abstract and generic.

    Negate : Negate_MethodGroup
    class Negate_MethodGroup:
        @typing.overload
        def __call__(self, value: Matrix) -> Matrix:...
        @typing.overload
        def __call__(self, value: clr.Reference[Matrix], result: clr.Reference[Matrix]) -> None:...

    # Skipped OrthoLH due to it being static, abstract and generic.

    OrthoLH : OrthoLH_MethodGroup
    class OrthoLH_MethodGroup:
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped OrthoOffCenterLH due to it being static, abstract and generic.

    OrthoOffCenterLH : OrthoOffCenterLH_MethodGroup
    class OrthoOffCenterLH_MethodGroup:
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped OrthoOffCenterRH due to it being static, abstract and generic.

    OrthoOffCenterRH : OrthoOffCenterRH_MethodGroup
    class OrthoOffCenterRH_MethodGroup:
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped OrthoRH due to it being static, abstract and generic.

    OrthoRH : OrthoRH_MethodGroup
    class OrthoRH_MethodGroup:
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped PerspectiveFovLH due to it being static, abstract and generic.

    PerspectiveFovLH : PerspectiveFovLH_MethodGroup
    class PerspectiveFovLH_MethodGroup:
        @typing.overload
        def __call__(self, fov: float, aspect: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, fov: float, aspect: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped PerspectiveFovRH due to it being static, abstract and generic.

    PerspectiveFovRH : PerspectiveFovRH_MethodGroup
    class PerspectiveFovRH_MethodGroup:
        @typing.overload
        def __call__(self, fov: float, aspect: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, fov: float, aspect: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped PerspectiveLH due to it being static, abstract and generic.

    PerspectiveLH : PerspectiveLH_MethodGroup
    class PerspectiveLH_MethodGroup:
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped PerspectiveOffCenterLH due to it being static, abstract and generic.

    PerspectiveOffCenterLH : PerspectiveOffCenterLH_MethodGroup
    class PerspectiveOffCenterLH_MethodGroup:
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped PerspectiveOffCenterRH due to it being static, abstract and generic.

    PerspectiveOffCenterRH : PerspectiveOffCenterRH_MethodGroup
    class PerspectiveOffCenterRH_MethodGroup:
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, left: float, right: float, bottom: float, top: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped PerspectiveRH due to it being static, abstract and generic.

    PerspectiveRH : PerspectiveRH_MethodGroup
    class PerspectiveRH_MethodGroup:
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float) -> Matrix:...
        @typing.overload
        def __call__(self, width: float, height: float, znear: float, zfar: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped RotationAxis due to it being static, abstract and generic.

    RotationAxis : RotationAxis_MethodGroup
    class RotationAxis_MethodGroup:
        @typing.overload
        def __call__(self, axis: Vector3, angle: float) -> Matrix:...
        @typing.overload
        def __call__(self, axis: clr.Reference[Vector3], angle: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped RotationQuaternion due to it being static, abstract and generic.

    RotationQuaternion : RotationQuaternion_MethodGroup
    class RotationQuaternion_MethodGroup:
        @typing.overload
        def __call__(self, rotation: Quaternion) -> Matrix:...
        @typing.overload
        def __call__(self, rotation: clr.Reference[Quaternion], result: clr.Reference[Matrix]) -> None:...

    # Skipped RotationX due to it being static, abstract and generic.

    RotationX : RotationX_MethodGroup
    class RotationX_MethodGroup:
        @typing.overload
        def __call__(self, angle: float) -> Matrix:...
        @typing.overload
        def __call__(self, angle: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped RotationY due to it being static, abstract and generic.

    RotationY : RotationY_MethodGroup
    class RotationY_MethodGroup:
        @typing.overload
        def __call__(self, angle: float) -> Matrix:...
        @typing.overload
        def __call__(self, angle: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped RotationYawPitchRoll due to it being static, abstract and generic.

    RotationYawPitchRoll : RotationYawPitchRoll_MethodGroup
    class RotationYawPitchRoll_MethodGroup:
        @typing.overload
        def __call__(self, yaw: float, pitch: float, roll: float) -> Matrix:...
        @typing.overload
        def __call__(self, yaw: float, pitch: float, roll: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped RotationZ due to it being static, abstract and generic.

    RotationZ : RotationZ_MethodGroup
    class RotationZ_MethodGroup:
        @typing.overload
        def __call__(self, angle: float) -> Matrix:...
        @typing.overload
        def __call__(self, angle: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped Scaling due to it being static, abstract and generic.

    Scaling : Scaling_MethodGroup
    class Scaling_MethodGroup:
        @typing.overload
        def __call__(self, scale: float) -> Matrix:...
        @typing.overload
        def __call__(self, scale: Vector3) -> Matrix:...
        @typing.overload
        def __call__(self, scale: float, result: clr.Reference[Matrix]) -> None:...
        @typing.overload
        def __call__(self, scale: clr.Reference[Vector3], result: clr.Reference[Matrix]) -> None:...
        @typing.overload
        def __call__(self, x: float, y: float, z: float) -> Matrix:...
        @typing.overload
        def __call__(self, x: float, y: float, z: float, result: clr.Reference[Matrix]) -> None:...

    # Skipped Subtract due to it being static, abstract and generic.

    Subtract : Subtract_MethodGroup
    class Subtract_MethodGroup:
        @typing.overload
        def __call__(self, left: Matrix, right: Matrix) -> Matrix:...
        @typing.overload
        def __call__(self, left: clr.Reference[Matrix], right: clr.Reference[Matrix], result: clr.Reference[Matrix]) -> None:...

    # Skipped ToString due to it being static, abstract and generic.

    ToString : ToString_MethodGroup
    class ToString_MethodGroup:
        @typing.overload
        def __call__(self) -> str:...
        @typing.overload
        def __call__(self, format: str) -> str:...
        @typing.overload
        def __call__(self, formatProvider: IFormatProvider) -> str:...
        @typing.overload
        def __call__(self, format: str, formatProvider: IFormatProvider) -> str:...

    # Skipped Translation due to it being static, abstract and generic.

    Translation : Translation_MethodGroup
    class Translation_MethodGroup:
        @typing.overload
        def __call__(self, value: Vector3) -> Matrix:...
        @typing.overload
        def __call__(self, value: clr.Reference[Vector3], result: clr.Reference[Matrix]) -> None:...
        @typing.overload
        def __call__(self, x: float, y: float, z: float) -> Matrix:...
        @typing.overload
        def __call__(self, x: float, y: float, z: float, result: clr.Reference[Matrix]) -> None:...



class ModelObject:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, reader: BinaryReader, model: Model) -> None: ...
    Indices : typing.List[int]
    Textures : typing.List[str]
    Vertices : List_1[VertexStruct]
    @property
    def bool_0(self) -> bool: ...
    @bool_0.setter
    def bool_0(self, value: bool) -> bool: ...
    @property
    def class252_0(self) -> Class252: ...
    @class252_0.setter
    def class252_0(self, value: Class252) -> Class252: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> str: ...
    @property
    def ObjectDefinitions(self) -> List_1[ModelObjectDefinition]: ...
    @ObjectDefinitions.setter
    def ObjectDefinitions(self, value: List_1[ModelObjectDefinition]) -> List_1[ModelObjectDefinition]: ...
    @property
    def ParentName(self) -> str: ...
    @ParentName.setter
    def ParentName(self, value: str) -> str: ...
    @property
    def ParentObject(self) -> ModelObject: ...
    @ParentObject.setter
    def ParentObject(self, value: ModelObject) -> ModelObject: ...
    @property
    def Position(self) -> Vector3: ...
    @Position.setter
    def Position(self, value: Vector3) -> Vector3: ...
    @property
    def TranslationVector(self) -> Vector3: ...
    @TranslationVector.setter
    def TranslationVector(self, value: Vector3) -> Vector3: ...
    @property
    def UnkQuat0(self) -> Quaternion: ...
    @UnkQuat0.setter
    def UnkQuat0(self, value: Quaternion) -> Quaternion: ...
    @property
    def UnkQuat1(self) -> Quaternion: ...
    @UnkQuat1.setter
    def UnkQuat1(self, value: Quaternion) -> Quaternion: ...
    @property
    def UnkQuat2(self) -> Quaternion: ...
    @UnkQuat2.setter
    def UnkQuat2(self, value: Quaternion) -> Quaternion: ...
    @property
    def UnkVec30(self) -> Vector3: ...
    @UnkVec30.setter
    def UnkVec30(self, value: Vector3) -> Vector3: ...
    @property
    def UnkVec31(self) -> Vector3: ...
    @UnkVec31.setter
    def UnkVec31(self, value: Vector3) -> Vector3: ...
    @property
    def UnusedRotationMatrix0(self) -> Quaternion: ...
    @UnusedRotationMatrix0.setter
    def UnusedRotationMatrix0(self, value: Quaternion) -> Quaternion: ...
    @property
    def UnusedRotationMatrix1(self) -> Quaternion: ...
    @UnusedRotationMatrix1.setter
    def UnusedRotationMatrix1(self, value: Quaternion) -> Quaternion: ...
    @property
    def UnusedScalingMatrix0(self) -> Matrix: ...
    @UnusedScalingMatrix0.setter
    def UnusedScalingMatrix0(self, value: Matrix) -> Matrix: ...
    @property
    def UnusedScalingMatrix1(self) -> Matrix: ...
    @UnusedScalingMatrix1.setter
    def UnusedScalingMatrix1(self, value: Matrix) -> Matrix: ...


class ModelObjectDefinition:
    def __init__(self) -> None: ...
    @property
    def BaseVertexLocation(self) -> int: ...
    @BaseVertexLocation.setter
    def BaseVertexLocation(self, value: int) -> int: ...
    @property
    def IndexCountPerInstance(self) -> int: ...
    @IndexCountPerInstance.setter
    def IndexCountPerInstance(self, value: int) -> int: ...
    @property
    def StartIndexLocation(self) -> int: ...
    @StartIndexLocation.setter
    def StartIndexLocation(self, value: int) -> int: ...
    @property
    def texture2D_0(self) -> str: ...
    @texture2D_0.setter
    def texture2D_0(self, value: str) -> str: ...
    @property
    def texture2D_1(self) -> str: ...
    @texture2D_1.setter
    def texture2D_1(self, value: str) -> str: ...
    @property
    def texture2D_2(self) -> str: ...
    @texture2D_2.setter
    def texture2D_2(self, value: str) -> str: ...


class ProceduralVegetation:
    def __init__(self) -> None: ...
    @property
    def PlantCount(self) -> int: ...
    @PlantCount.setter
    def PlantCount(self, value: int) -> int: ...
    @property
    def Plants(self) -> List_1[Vector4]: ...
    @Plants.setter
    def Plants(self, value: List_1[Vector4]) -> List_1[Vector4]: ...
    @property
    def TileXZ(self) -> TileIndex: ...
    @TileXZ.setter
    def TileXZ(self, value: TileIndex) -> TileIndex: ...


class Quaternion(IFormattable):
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @typing.overload
    def __init__(self, value: Vector4) -> None: ...
    @typing.overload
    def __init__(self, value: Vector3, w: float) -> None: ...
    @typing.overload
    def __init__(self, value: Vector2, z: float, w: float) -> None: ...
    @typing.overload
    def __init__(self, values: typing.List[float]) -> None: ...
    @typing.overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    Identity : Quaternion
    One : Quaternion
    SizeInBytes : int
    Zero : Quaternion
    @property
    def IsIdentity(self) -> bool: ...
    @property
    def Item(self) -> float: ...
    @Item.setter
    def Item(self, value: float) -> float: ...
    @property
    def W(self) -> float: ...
    @W.setter
    def W(self, value: float) -> float: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    @property
    def Z(self) -> float: ...
    @Z.setter
    def Z(self, value: float) -> float: ...
    def Equals(self, other: clr.Reference[Quaternion]) -> bool: ...
    def GetHashCode(self) -> int: ...
    def Length(self) -> float: ...
    def LengthSquared(self) -> float: ...
    def Normalize(self) -> None: ...
    def __add__(self, left: Quaternion, right: Quaternion) -> Quaternion: ...
    def __eq__(self, left: Quaternion, right: Quaternion) -> bool: ...
    def __ne__(self, left: Quaternion, right: Quaternion) -> bool: ...
    @typing.overload
    def __mul__(self, scale: float, value: Quaternion) -> Quaternion: ...
    @typing.overload
    def __mul__(self, value: Quaternion, scale: float) -> Quaternion: ...
    @typing.overload
    def __mul__(self, left: Quaternion, right: Quaternion) -> Quaternion: ...
    def __sub__(self, left: Quaternion, right: Quaternion) -> Quaternion: ...
    def __neg__(self, value: Quaternion) -> Quaternion: ...
    def ToArray(self) -> typing.List[float]: ...
    # Skipped Add due to it being static, abstract and generic.

    Add : Add_MethodGroup
    class Add_MethodGroup:
        @typing.overload
        def __call__(self, left: Quaternion, right: Quaternion) -> Quaternion:...
        @typing.overload
        def __call__(self, left: clr.Reference[Quaternion], right: clr.Reference[Quaternion], result: clr.Reference[Quaternion]) -> None:...

    # Skipped Conjugate due to it being static, abstract and generic.

    Conjugate : Conjugate_MethodGroup
    class Conjugate_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, value: Quaternion) -> Quaternion:...
        @typing.overload
        def __call__(self, value: clr.Reference[Quaternion], result: clr.Reference[Quaternion]) -> None:...

    # Skipped Dot due to it being static, abstract and generic.

    Dot : Dot_MethodGroup
    class Dot_MethodGroup:
        @typing.overload
        def __call__(self, left: Quaternion, right: Quaternion) -> float:...
        @typing.overload
        def __call__(self, left: clr.Reference[Quaternion], right: clr.Reference[Quaternion], result: clr.Reference[float]) -> None:...

    # Skipped Lerp due to it being static, abstract and generic.

    Lerp : Lerp_MethodGroup
    class Lerp_MethodGroup:
        @typing.overload
        def __call__(self, start: Quaternion, end: Quaternion, amount: float) -> Quaternion:...
        @typing.overload
        def __call__(self, start: clr.Reference[Quaternion], end: clr.Reference[Quaternion], amount: float, result: clr.Reference[Quaternion]) -> None:...

    # Skipped Multiply due to it being static, abstract and generic.

    Multiply : Multiply_MethodGroup
    class Multiply_MethodGroup:
        @typing.overload
        def __call__(self, value: Quaternion, scale: float) -> Quaternion:...
        @typing.overload
        def __call__(self, left: Quaternion, right: Quaternion) -> Quaternion:...
        @typing.overload
        def __call__(self, value: clr.Reference[Quaternion], scale: float, result: clr.Reference[Quaternion]) -> None:...
        @typing.overload
        def __call__(self, left: clr.Reference[Quaternion], right: clr.Reference[Quaternion], result: clr.Reference[Quaternion]) -> None:...

    # Skipped Negate due to it being static, abstract and generic.

    Negate : Negate_MethodGroup
    class Negate_MethodGroup:
        @typing.overload
        def __call__(self, value: Quaternion) -> Quaternion:...
        @typing.overload
        def __call__(self, value: clr.Reference[Quaternion], result: clr.Reference[Quaternion]) -> None:...

    # Skipped RotationMatrix due to it being static, abstract and generic.

    RotationMatrix : RotationMatrix_MethodGroup
    class RotationMatrix_MethodGroup:
        @typing.overload
        def __call__(self, matrix: Matrix) -> Quaternion:...
        @typing.overload
        def __call__(self, matrix: clr.Reference[Matrix], result: clr.Reference[Quaternion]) -> None:...

    # Skipped RotationYawPitchRoll due to it being static, abstract and generic.

    RotationYawPitchRoll : RotationYawPitchRoll_MethodGroup
    class RotationYawPitchRoll_MethodGroup:
        @typing.overload
        def __call__(self, yaw: float, pitch: float, roll: float) -> Quaternion:...
        @typing.overload
        def __call__(self, yaw: float, pitch: float, roll: float, result: clr.Reference[Quaternion]) -> None:...

    # Skipped Subtract due to it being static, abstract and generic.

    Subtract : Subtract_MethodGroup
    class Subtract_MethodGroup:
        @typing.overload
        def __call__(self, left: Quaternion, right: Quaternion) -> Quaternion:...
        @typing.overload
        def __call__(self, left: clr.Reference[Quaternion], right: clr.Reference[Quaternion], result: clr.Reference[Quaternion]) -> None:...

    # Skipped ToString due to it being static, abstract and generic.

    ToString : ToString_MethodGroup
    class ToString_MethodGroup:
        @typing.overload
        def __call__(self) -> str:...
        @typing.overload
        def __call__(self, format: str) -> str:...
        @typing.overload
        def __call__(self, formatProvider: IFormatProvider) -> str:...
        @typing.overload
        def __call__(self, format: str, formatProvider: IFormatProvider) -> str:...



class Rectangle:
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @property
    def Height(self) -> int: ...
    @Height.setter
    def Height(self, value: int) -> int: ...
    @property
    def Width(self) -> int: ...
    @Width.setter
    def Width(self, value: int) -> int: ...
    @property
    def X(self) -> int: ...
    @X.setter
    def X(self, value: int) -> int: ...
    @property
    def Y(self) -> int: ...
    @Y.setter
    def Y(self, value: int) -> int: ...
    def ToString(self) -> str: ...


class Route:
    def __init__(self) -> None: ...
    @property
    def BlockDetectorIndices(self) -> List_1[int]: ...
    @BlockDetectorIndices.setter
    def BlockDetectorIndices(self, value: List_1[int]) -> List_1[int]: ...
    @property
    def bool_0(self) -> bool: ...
    @bool_0.setter
    def bool_0(self, value: bool) -> bool: ...
    @property
    def bool_1(self) -> bool: ...
    @bool_1.setter
    def bool_1(self, value: bool) -> bool: ...
    @property
    def bool_10(self) -> bool: ...
    @bool_10.setter
    def bool_10(self, value: bool) -> bool: ...
    @property
    def bool_11(self) -> bool: ...
    @bool_11.setter
    def bool_11(self, value: bool) -> bool: ...
    @property
    def bool_12(self) -> bool: ...
    @bool_12.setter
    def bool_12(self, value: bool) -> bool: ...
    @property
    def bool_13(self) -> bool: ...
    @bool_13.setter
    def bool_13(self, value: bool) -> bool: ...
    @property
    def bool_14(self) -> bool: ...
    @bool_14.setter
    def bool_14(self, value: bool) -> bool: ...
    @property
    def bool_15(self) -> bool: ...
    @bool_15.setter
    def bool_15(self, value: bool) -> bool: ...
    @property
    def bool_16(self) -> bool: ...
    @bool_16.setter
    def bool_16(self, value: bool) -> bool: ...
    @property
    def bool_17(self) -> bool: ...
    @bool_17.setter
    def bool_17(self, value: bool) -> bool: ...
    @property
    def bool_18(self) -> bool: ...
    @bool_18.setter
    def bool_18(self, value: bool) -> bool: ...
    @property
    def bool_2(self) -> bool: ...
    @bool_2.setter
    def bool_2(self, value: bool) -> bool: ...
    @property
    def bool_3(self) -> bool: ...
    @bool_3.setter
    def bool_3(self, value: bool) -> bool: ...
    @property
    def bool_4(self) -> bool: ...
    @bool_4.setter
    def bool_4(self, value: bool) -> bool: ...
    @property
    def bool_5(self) -> bool: ...
    @bool_5.setter
    def bool_5(self, value: bool) -> bool: ...
    @property
    def bool_6(self) -> bool: ...
    @bool_6.setter
    def bool_6(self, value: bool) -> bool: ...
    @property
    def bool_7(self) -> bool: ...
    @bool_7.setter
    def bool_7(self, value: bool) -> bool: ...
    @property
    def bool_8(self) -> bool: ...
    @bool_8.setter
    def bool_8(self, value: bool) -> bool: ...
    @property
    def bool_9(self) -> bool: ...
    @bool_9.setter
    def bool_9(self, value: bool) -> bool: ...
    @property
    def enum61(self) -> Enum61: ...
    @enum61.setter
    def enum61(self, value: Enum61) -> Enum61: ...
    @property
    def PrevSignalIndices(self) -> List_1[int]: ...
    @PrevSignalIndices.setter
    def PrevSignalIndices(self, value: List_1[int]) -> List_1[int]: ...
    @property
    def ReadFromDatabasePrefix(self) -> int: ...
    @ReadFromDatabasePrefix.setter
    def ReadFromDatabasePrefix(self, value: int) -> int: ...
    @property
    def RouteMaxMPH(self) -> int: ...
    @RouteMaxMPH.setter
    def RouteMaxMPH(self, value: int) -> int: ...
    @property
    def RouteName(self) -> str: ...
    @RouteName.setter
    def RouteName(self, value: str) -> str: ...
    @property
    def SwitchList(self) -> List_1[SignalSwitchConnection]: ...
    @SwitchList.setter
    def SwitchList(self, value: List_1[SignalSwitchConnection]) -> List_1[SignalSwitchConnection]: ...
    @staticmethod
    def Read(reader: BinaryReader) -> Route: ...


class SceneryAssetLoader:
    def __init__(self) -> None: ...
    @property
    def Bool0(self) -> bool: ...
    @Bool0.setter
    def Bool0(self, value: bool) -> bool: ...
    @property
    def DecalLoadList(self) -> List_1[DecalLoader]: ...
    @DecalLoadList.setter
    def DecalLoadList(self, value: List_1[DecalLoader]) -> List_1[DecalLoader]: ...
    @property
    def DisregardBoundingTest(self) -> bool: ...
    @DisregardBoundingTest.setter
    def DisregardBoundingTest(self, value: bool) -> bool: ...
    @property
    def ModelName(self) -> str: ...
    @ModelName.setter
    def ModelName(self, value: str) -> str: ...
    @property
    def PositionXYZ(self) -> Vector3: ...
    @PositionXYZ.setter
    def PositionXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def RotationXYZ(self) -> Vector3: ...
    @RotationXYZ.setter
    def RotationXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def Scale(self) -> Vector3: ...
    @Scale.setter
    def Scale(self, value: Vector3) -> Vector3: ...
    @property
    def TileXZ(self) -> TileIndex: ...
    @TileXZ.setter
    def TileXZ(self, value: TileIndex) -> TileIndex: ...


class SignalHead:
    def __init__(self) -> None: ...
    @property
    def bool_2(self) -> bool: ...
    @bool_2.setter
    def bool_2(self, value: bool) -> bool: ...
    @property
    def bool_3(self) -> bool: ...
    @bool_3.setter
    def bool_3(self, value: bool) -> bool: ...
    @property
    def bool_4(self) -> bool: ...
    @bool_4.setter
    def bool_4(self, value: bool) -> bool: ...
    @property
    def bool_5(self) -> bool: ...
    @bool_5.setter
    def bool_5(self, value: bool) -> bool: ...
    @property
    def IsAbsolute(self) -> bool: ...
    @IsAbsolute.setter
    def IsAbsolute(self, value: bool) -> bool: ...
    @property
    def IsAdvanceDiverging(self) -> bool: ...
    @IsAdvanceDiverging.setter
    def IsAdvanceDiverging(self, value: bool) -> bool: ...
    @property
    def IsDwarf(self) -> bool: ...
    @IsDwarf.setter
    def IsDwarf(self, value: bool) -> bool: ...
    @property
    def LeastRestrictiveSignalState(self) -> int: ...
    @LeastRestrictiveSignalState.setter
    def LeastRestrictiveSignalState(self, value: int) -> int: ...
    @property
    def ModelName(self) -> str: ...
    @ModelName.setter
    def ModelName(self, value: str) -> str: ...
    @property
    def Position(self) -> Vector3: ...
    @Position.setter
    def Position(self, value: Vector3) -> Vector3: ...
    @property
    def RotationDegY(self) -> float: ...
    @RotationDegY.setter
    def RotationDegY(self, value: float) -> float: ...
    @property
    def Routes(self) -> List_1[Route]: ...
    @Routes.setter
    def Routes(self, value: List_1[Route]) -> List_1[Route]: ...
    @property
    def SignalIndex(self) -> int: ...
    @SignalIndex.setter
    def SignalIndex(self, value: int) -> int: ...
    @property
    def SignalIndices(self) -> List_1[int]: ...
    @SignalIndices.setter
    def SignalIndices(self, value: List_1[int]) -> List_1[int]: ...
    @property
    def TileXZ(self) -> TileIndex: ...
    @TileXZ.setter
    def TileXZ(self, value: TileIndex) -> TileIndex: ...
    @staticmethod
    def Read(reader: BinaryReader) -> SignalHead: ...


class SignalSwitchConnection:
    def __init__(self) -> None: ...
    @property
    def ClearIfThrownNormal(self) -> bool: ...
    @ClearIfThrownNormal.setter
    def ClearIfThrownNormal(self, value: bool) -> bool: ...
    @property
    def SwitchIndex(self) -> int: ...
    @SwitchIndex.setter
    def SwitchIndex(self, value: int) -> int: ...
    @staticmethod
    def Read(reader: BinaryReader) -> SignalSwitchConnection: ...


class TileIndex:
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, x: int, y: int) -> None: ...
    @property
    def X(self) -> int: ...
    @X.setter
    def X(self, value: int) -> int: ...
    @property
    def Z(self) -> int: ...
    @Z.setter
    def Z(self, value: int) -> int: ...
    @staticmethod
    def Read(reader: BinaryReader) -> TileIndex: ...


class TrackNode:
    def __init__(self) -> None: ...
    @property
    def ArcLengthMeters(self) -> float: ...
    @ArcLengthMeters.setter
    def ArcLengthMeters(self, value: float) -> float: ...
    @property
    def BelongsToTrackIndex(self) -> int: ...
    @BelongsToTrackIndex.setter
    def BelongsToTrackIndex(self, value: int) -> int: ...
    @property
    def CurvatureDeg(self) -> float: ...
    @CurvatureDeg.setter
    def CurvatureDeg(self, value: float) -> float: ...
    @property
    def CurveSign(self) -> int: ...
    @CurveSign.setter
    def CurveSign(self, value: int) -> int: ...
    @property
    def EndPositionXYZ(self) -> Vector3: ...
    @EndPositionXYZ.setter
    def EndPositionXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def IsReversePath(self) -> bool: ...
    @IsReversePath.setter
    def IsReversePath(self, value: bool) -> bool: ...
    @property
    def IsSelected(self) -> bool: ...
    @IsSelected.setter
    def IsSelected(self, value: bool) -> bool: ...
    @property
    def IsSwitchNode(self) -> bool: ...
    @IsSwitchNode.setter
    def IsSwitchNode(self, value: bool) -> bool: ...
    @property
    def NodeIndex(self) -> int: ...
    @NodeIndex.setter
    def NodeIndex(self, value: int) -> int: ...
    @property
    def NumSegments(self) -> int: ...
    @NumSegments.setter
    def NumSegments(self, value: int) -> int: ...
    @property
    def Position(self) -> Vector3: ...
    @Position.setter
    def Position(self, value: Vector3) -> Vector3: ...
    @property
    def RadiusMeters(self) -> float: ...
    @RadiusMeters.setter
    def RadiusMeters(self, value: float) -> float: ...
    @property
    def TangentDegXYZ(self) -> Vector3: ...
    @TangentDegXYZ.setter
    def TangentDegXYZ(self, value: Vector3) -> Vector3: ...
    @property
    def TileIndex(self) -> TileIndex: ...
    @TileIndex.setter
    def TileIndex(self, value: TileIndex) -> TileIndex: ...
    def Read(self, reader: BinaryReader) -> None: ...


class TrackSection:
    def __init__(self) -> None: ...
    @property
    def Index(self) -> int: ...
    @Index.setter
    def Index(self, value: int) -> int: ...
    @property
    def IsCTCSwitch(self) -> bool: ...
    @IsCTCSwitch.setter
    def IsCTCSwitch(self, value: bool) -> bool: ...
    @property
    def IsOccupied(self) -> bool: ...
    @IsOccupied.setter
    def IsOccupied(self, value: bool) -> bool: ...
    @property
    def NextSectionIndex(self) -> typing.List[int]: ...
    @NextSectionIndex.setter
    def NextSectionIndex(self, value: typing.List[int]) -> typing.List[int]: ...
    @property
    def Nodes(self) -> typing.List[TrackNode]: ...
    @Nodes.setter
    def Nodes(self, value: typing.List[TrackNode]) -> typing.List[TrackNode]: ...
    @property
    def RetarderMPH(self) -> float: ...
    @RetarderMPH.setter
    def RetarderMPH(self, value: float) -> float: ...
    @property
    def SwitchLeverPosition(self) -> bool: ...
    @SwitchLeverPosition.setter
    def SwitchLeverPosition(self, value: bool) -> bool: ...
    @property
    def SwitchStandLeftSide(self) -> bool: ...
    @SwitchStandLeftSide.setter
    def SwitchStandLeftSide(self, value: bool) -> bool: ...
    @property
    def SwitchStandType(self) -> int: ...
    @SwitchStandType.setter
    def SwitchStandType(self, value: int) -> int: ...
    @property
    def TrackType(self) -> int: ...
    @TrackType.setter
    def TrackType(self, value: int) -> int: ...
    def Read(self, reader: BinaryReader) -> None: ...


class Vector2:
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @typing.overload
    def __init__(self, x: float, y: float) -> None: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    def ToString(self) -> str: ...


class Vector3:
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @typing.overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    BackwardLH : Vector3
    BackwardRH : Vector3
    Down : Vector3
    ForwardLH : Vector3
    ForwardRH : Vector3
    Left : Vector3
    One : Vector3
    Right : Vector3
    Up : Vector3
    Zero : Vector3
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    @property
    def Z(self) -> float: ...
    @Z.setter
    def Z(self, value: float) -> float: ...
    @staticmethod
    def IsZero(a: float) -> bool: ...
    def Length(self) -> float: ...
    def __add__(self, left: Vector3, right: Vector3) -> Vector3: ...
    def __eq__(self, left: Vector3, right: Vector3) -> bool: ...
    def __ne__(self, left: Vector3, right: Vector3) -> bool: ...
    @typing.overload
    def __mul__(self, scale: float, value: Vector3) -> Vector3: ...
    @typing.overload
    def __mul__(self, value: Vector3, scale: float) -> Vector3: ...
    @typing.overload
    def __mul__(self, left: Vector3, right: Vector3) -> Vector3: ...
    @typing.overload
    def __sub__(self, scalar: float, value: Vector3) -> Vector3: ...
    @typing.overload
    def __sub__(self, value: Vector3, scalar: float) -> Vector3: ...
    @typing.overload
    def __sub__(self, left: Vector3, right: Vector3) -> Vector3: ...
    def __neg__(self, value: Vector3) -> Vector3: ...
    @staticmethod
    def Read(reader: BinaryReader) -> Vector3: ...
    def ToString(self) -> str: ...
    # Skipped Cross due to it being static, abstract and generic.

    Cross : Cross_MethodGroup
    class Cross_MethodGroup:
        @typing.overload
        def __call__(self, left: Vector3, right: Vector3) -> Vector3:...
        @typing.overload
        def __call__(self, left: clr.Reference[Vector3], right: clr.Reference[Vector3], result: clr.Reference[Vector3]) -> None:...

    # Skipped Lerp due to it being static, abstract and generic.

    Lerp : Lerp_MethodGroup
    class Lerp_MethodGroup:
        @typing.overload
        def __call__(self, start: Vector3, end: Vector3, amount: float) -> Vector3:...
        @typing.overload
        def __call__(self, start: clr.Reference[Vector3], end: clr.Reference[Vector3], amount: float, result: clr.Reference[Vector3]) -> None:...

    # Skipped Normalize due to it being static, abstract and generic.

    Normalize : Normalize_MethodGroup
    class Normalize_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, value: Vector3) -> Vector3:...

    # Skipped Transform due to it being static, abstract and generic.

    Transform : Transform_MethodGroup
    class Transform_MethodGroup:
        @typing.overload
        def __call__(self, vector: Vector3, rotation: Quaternion) -> Vector3:...
        @typing.overload
        def __call__(self, vector: Vector3, transform: Matrix) -> Vector4:...
        @typing.overload
        def __call__(self, source: typing.List[Vector3], rotation: clr.Reference[Quaternion], destination: typing.List[Vector3]) -> None:...
        @typing.overload
        def __call__(self, source: typing.List[Vector3], transform: clr.Reference[Matrix], destination: typing.List[Vector4]) -> None:...
        @typing.overload
        def __call__(self, vector: clr.Reference[Vector3], rotation: clr.Reference[Quaternion], result: clr.Reference[Vector3]) -> None:...
        @typing.overload
        def __call__(self, vector: clr.Reference[Vector3], transform: clr.Reference[Matrix], result: clr.Reference[Vector4]) -> None:...



class Vector4:
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @typing.overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @property
    def W(self) -> float: ...
    @W.setter
    def W(self, value: float) -> float: ...
    @property
    def X(self) -> float: ...
    @X.setter
    def X(self, value: float) -> float: ...
    @property
    def Y(self) -> float: ...
    @Y.setter
    def Y(self, value: float) -> float: ...
    @property
    def Z(self) -> float: ...
    @Z.setter
    def Z(self, value: float) -> float: ...


class VertexStruct:
    Binormal : Vector3
    Normal : Vector3
    Position : Vector3
    Tangent : Vector3
    TextureCoordinate : Vector2
    def ToString(self) -> str: ...

