import typing
from System import Array_1
from LibRun8.Common import VertexStruct, Vector2, SceneryAssetLoader, ProceduralVegetation, TileIndex
from System.Collections.Generic import List_1
from System.IO import BinaryReader

class Chunk:
    def __init__(self) -> None: ...
    CHUNK_SIZE : int
    HeightMap : typing.List[float]
    @property
    def CX(self) -> int: ...
    @CX.setter
    def CX(self, value: int) -> int: ...
    @property
    def CZ(self) -> int: ...
    @CZ.setter
    def CZ(self, value: int) -> int: ...
    @property
    def Hixels(self) -> int: ...
    @Hixels.setter
    def Hixels(self, value: int) -> int: ...
    @property
    def JaggedHeightMap(self) -> typing.List[typing.List[float]]: ...
    @property
    def Vertices(self) -> typing.List[VertexStruct]: ...
    @Vertices.setter
    def Vertices(self, value: typing.List[VertexStruct]) -> typing.List[VertexStruct]: ...


class ChunkStitcher:
    def __init__(self) -> None: ...
    @staticmethod
    def StitchChucks(chunkData: typing.List[Chunk]) -> None: ...


class ETileType(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    None_ : ETileType # 0
    Ter : ETileType # 1
    Tr2 : ETileType # 2
    Tr3 : ETileType # 3
    Tr4 : ETileType # 4


class Terrain:
    def __init__(self) -> None: ...
    @staticmethod
    def Read(path: str) -> TerrainTile: ...


class TerrainTile:
    def __init__(self) -> None: ...
    @property
    def AllVerticesTemp(self) -> typing.List[VertexStruct]: ...
    @AllVerticesTemp.setter
    def AllVerticesTemp(self, value: typing.List[VertexStruct]) -> typing.List[VertexStruct]: ...
    @property
    def CenterXZ(self) -> Vector2: ...
    @CenterXZ.setter
    def CenterXZ(self, value: Vector2) -> Vector2: ...
    @property
    def CenterY(self) -> float: ...
    @CenterY.setter
    def CenterY(self, value: float) -> float: ...
    @property
    def ChunkData(self) -> typing.List[Chunk]: ...
    @ChunkData.setter
    def ChunkData(self, value: typing.List[Chunk]) -> typing.List[Chunk]: ...
    @property
    def DetailLevel(self) -> int: ...
    @DetailLevel.setter
    def DetailLevel(self, value: int) -> int: ...
    @property
    def IndexBuffer(self) -> typing.List[int]: ...
    @IndexBuffer.setter
    def IndexBuffer(self, value: typing.List[int]) -> typing.List[int]: ...
    @property
    def LatNorth(self) -> float: ...
    @LatNorth.setter
    def LatNorth(self, value: float) -> float: ...
    @property
    def LatSouth(self) -> float: ...
    @LatSouth.setter
    def LatSouth(self, value: float) -> float: ...
    @property
    def LoadList(self) -> List_1[SceneryAssetLoader]: ...
    @LoadList.setter
    def LoadList(self, value: List_1[SceneryAssetLoader]) -> List_1[SceneryAssetLoader]: ...
    @property
    def LonEast(self) -> float: ...
    @LonEast.setter
    def LonEast(self, value: float) -> float: ...
    @property
    def LonWest(self) -> float: ...
    @LonWest.setter
    def LonWest(self, value: float) -> float: ...
    @property
    def Plants(self) -> ProceduralVegetation: ...
    @Plants.setter
    def Plants(self, value: ProceduralVegetation) -> ProceduralVegetation: ...
    @property
    def ProcVeg(self) -> str: ...
    @ProcVeg.setter
    def ProcVeg(self, value: str) -> str: ...
    @property
    def Texture0Name(self) -> str: ...
    @Texture0Name.setter
    def Texture0Name(self, value: str) -> str: ...
    @property
    def Texture1Name(self) -> str: ...
    @Texture1Name.setter
    def Texture1Name(self, value: str) -> str: ...
    @property
    def Texture2Name(self) -> str: ...
    @Texture2Name.setter
    def Texture2Name(self, value: str) -> str: ...
    @property
    def Texture3Name(self) -> str: ...
    @Texture3Name.setter
    def Texture3Name(self, value: str) -> str: ...
    @property
    def TileXZ(self) -> TileIndex: ...
    @TileXZ.setter
    def TileXZ(self, value: TileIndex) -> TileIndex: ...
    @property
    def WeightMap(self) -> typing.List[int]: ...
    @WeightMap.setter
    def WeightMap(self, value: typing.List[int]) -> typing.List[int]: ...
    def CopyToVertexBuffers(self) -> None: ...
    def WriteOBJ(self, path: str) -> None: ...


class TerrainTileLoadData:
    def __init__(self) -> None: ...
    @property
    def FileNameOnly(self) -> str: ...
    @FileNameOnly.setter
    def FileNameOnly(self, value: str) -> str: ...
    @property
    def FilePath(self) -> str: ...
    @FilePath.setter
    def FilePath(self, value: str) -> str: ...
    @property
    def Tile(self) -> TerrainTile: ...
    @Tile.setter
    def Tile(self, value: TerrainTile) -> TerrainTile: ...
    @property
    def Type(self) -> ETileType: ...
    @Type.setter
    def Type(self, value: ETileType) -> ETileType: ...


class Tr2Loader:
    def __init__(self) -> None: ...
    @staticmethod
    def LoadChunks(reader: BinaryReader, terrainTileLoadData: TerrainTileLoadData) -> None: ...
    def Write(self, path: str) -> None: ...
    # Skipped LoadTile due to it being static, abstract and generic.

    LoadTile : LoadTile_MethodGroup
    class LoadTile_MethodGroup:
        @typing.overload
        def __call__(self, terrainTileLoadData: TerrainTileLoadData) -> None:...
        @typing.overload
        def __call__(self, terrainTileLoadData: TerrainTileLoadData, bool0: bool) -> None:...



class Tr4Loader:
    def __init__(self) -> None: ...
    @staticmethod
    def LoadTile(terrainTileLoadData: TerrainTileLoadData, bool0: bool) -> None: ...

